name = "fortran-csv-module"
version = "2.0.1"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2017-2023, Jacob Williams"
license = "BSD-3"
description = "Read and Write CSV Files Using Modern Fortran"
homepage = "https://github.com/jacobwilliams/fortran-csv-module"
categories = ["io"]
keywords = ["csv"]

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = true
auto-examples = true
auto-tests = true